### ISSUE TITLE
Animation example

### ISSUE THREAD

**Issue by kolia** [fonsp/PlutoUI.jl#1]
Nice work on fonsp/Pluto.jl#17, design looks nice and works like a charm.

How would you recommend doing animations? One can now drive animations from javascript by doing something along the lines of:

```
@bind t html"""
<div id='time'>
	<input id='speed' type='range' min='-1' max='1'/>
	<label id='time' for='speed'/>
	<script>
		const time  = document.querySelector("div#time")
		const label = document.querySelector("label#time")
		const speed = document.querySelector("input#speed")
		let t = 0;
		setInterval(dt, 10);
		function dt()
		{
      	   t = t + speed.valueAsNumber * 0.01;
		   time.value = t;
		   label.innerHTML = t.toFixed(2);
		   time.dispatchEvent(new CustomEvent("input"))
		}
	</script>
</div>
"""
```

and then using `t` to animate other cells.

@fonsp is there a better / simpler way you'd recommend?

I also tried driving an animation from julia, using `@async` or `@spawn` to increment a global time variable in the background. The time variable does get updated, but the asynchronous updates do not trigger reactive evaluation of dependent cells. Is there is a way to trigger reactive eval from asynchronous blocks of code?

**Comment by fonsp** [comment]
I have added `PlutoUI.Timer`, try it out!

![plutotimer](https://user-images.githubusercontent.com/6933510/80591092-5e5c1880-8a1d-11ea-9a9d-15014de86be6.gif)
