### ISSUE TITLE
Usage of Button?

### ISSUE THREAD

**Issue by zenon** [fonsp/PlutoUI.jl#10]
Hi,

can you please tell me how to use the Button? It always seems to have the value given as argument "label" to the constructor.

Thank you!, z.

**Comment by fonsp** [comment]
That's right - it does not make a lot of sense in most cases!

However, sometimes it can be useful to "trigger reactivity", for example:

```julia
@bind go Button("Go!")
```

```julia
data = let
    go # we reference `go`, making this cell a dependency of the first cell
    rand(100)
end
```

```julia
sum(data)
```

When you click `Go!`, the other two cells start running. So it's useful when you have code that does something different every time (this example), or code that creates _side effects_, like writing to a file or appending to an array.

**Comment by fonsp** [comment]
You can use a `CheckBox` if you want to know the toggled state.

**Comment by zenon** [comment]
Nice trick. Thank you!
