### ISSUE TITLE
Show value of slider next to it

### ISSUE THREAD

**Issue by briochemc** [fonsp/PlutoUI.jl#11]
Is it possible to show the value of the slider in the same cell in Pluto? I think not from 

> #### Separate definition and reference
> 
> If you put a bond and a reference to the same variable together, it will keep evaluating in a loop.
> 
> So **do not** write
> ```julia
> md""\"$(@bind r html"<input type='range'>")  $(r^2)""\"
> ```
> 
> Instead, create two cells:
> ```julia
> md""\"$(@bind r html"<input type='range'>")""\"
> ```
> ```julia
> r^2
> ```

but maybe I missed something? I would like something like

```julia
begin
	r_slider = @bind r html"<input type='range'>"
	md"""
	r = $r $r_slider
	"""
end
```

**Comment by barucden** [comment]
Hey! I have just started using Pluto, and I think it is awesome. Great job!

Anyway... I would appreciate to have this feature too. I have implemented a solution and I am curious about your opinion.
```julia
struct MySlider 
    range::AbstractRange
    default::Number
end
function Base.show(io::IO, ::MIME"text/html", slider::MySlider)
    print(io, """
		<input type="range" 
		min="$(first(slider.range))" 
		step="$(step(slider.range))"
		max="$(last(slider.range))" 
		value="$(slider.default)"
		oninput="this.nextElementSibling.value=this.value">
		<output>$(slider.default)</output>""")
end
```
Use it just like the standard slider:
```julia
md"Input: $(@bind n MySlider(1:100, 10))"
```
There is no javascript (well, there is, but only a small inline one), and it only differs from the standard `Slider` in the `show` method. We could extend the current slider implementation by adding another field (`display`?) that would control whether the output is rendered or not.

What do you think? Is there any problem with the solution? 

I can open a PR if you'd like me to.

**Comment by fonsp** [comment]
Awesome! This is perfect 👍 Can you post a screenshot? Does it look OK when you have very large bounds (`1e50`) or when you have floating point values? (`1.0/3.0`)

Yes, make it a PR! I think this should be a keyword argument to the `Slider` constructor, with default value `false`.

**Comment by barucden** [comment]
Yes, sure. I could not get past `1e18` as Julia was throwing `InexactError`, but here are some screenshots.

![Screenshot-14](https://user-images.githubusercontent.com/13768925/89223131-8b006d00-d5d6-11ea-9d10-1c5e9c105db3.png)
![Screenshot-15](https://user-images.githubusercontent.com/13768925/89223132-8b006d00-d5d6-11ea-8b4b-156201f2920d.png)
![Screenshot-16](https://user-images.githubusercontent.com/13768925/89223134-8b990380-d5d6-11ea-883f-217f9e111449.png)

**Comment by fonsp** [comment]
Good enough for now! Look forward to adding your PR!

**Comment by putianyi889** [comment]
Can we format the string shown? For example, scientific notation and number of digits.
