### ISSUE TITLE
Layout problems with long MultiCheckBox

### ISSUE THREAD

**Issue by yha** [fonsp/PlutoUI.jl#134]
Long `MultiCheckBox`s display with a scrollbar. I think they shouldn't, just like markdown seems to never trigger scrollbars. Or at least, I want a way to turn it off.
It doesn't help if I try to put the `MultiCheckBox` inside markdown. It seems to think it's smaller then it actually is.
```
mcb = MultiCheckBox(["option $i ($(String(rand('a':'z',10))))" for i=1:50])
```
```
let lorem = "lorem ipsum "^20
	md"""
	# a
	$mcb
	$lorem
	# b
	$mcb
	"""
end
```
![image](https://user-images.githubusercontent.com/4170948/132992817-3fced72d-ac04-42f8-ad47-71e5d9f23a32.png)

**Comment by fonsp** [comment]
Thanks! The scrollbar will be removed in the next release
