### ISSUE TITLE
`with_terminal()` with `println()` crashes when the string contains Chinese

### ISSUE THREAD

**Issue by likanzhan** [fonsp/PlutoUI.jl#141]
PlutoUI v0.7.11
This example works as expected:
```Julia
with_terminal() do
    println("hello, world!")
end
```
while this one does not:
```Julia
with_terminal() do
    println("你好，世界!")
end
```

**Comment by pankgeorg** [comment]
I just tried it and it works on Windows 11, Chrome, Julia 1.7/WSL

![image](https://user-images.githubusercontent.com/8681967/134774747-3e26487a-a075-4323-9253-5e79342e085f.png)

Can you share some more details for your setup?

Thanks!

**Comment by likanzhan** [comment]
Sorry, I also cannot reproduce my problem either. I don't know what happened. I will close it.

**Comment by likanzhan** [comment]
The problems re-occurs in version PlutoUI v0.7.12
<img width="624" alt="Screen Shot 2021-10-01 at 4 53 00 PM" src="https://user-images.githubusercontent.com/10531698/135593220-95265acd-416c-4c48-a732-15d60eb061ba.png">

**Comment by pankgeorg** [comment]
Can confirm this happens in v0.7.14 too. Looking into it.

**Comment by fonsp** [comment]
Thanks! I traced it back to https://github.com/MechanicalRabbit/HypertextLiteral.jl/issues/16

**Comment by likanzhan** [comment]
This has been resolved by an update of HypertextLiteral.jl, Thanks.
