### ISSUE TITLE
Feature request: Date and time widget

### ISSUE THREAD

**Issue by karlwessel** [fonsp/PlutoUI.jl#23]
A date and time selection widget that returns a `DateTime` would be nice. 

I can already get a string of the date and time with 
```
@bind dateandtime html"""<input type="datetime-local">"""
```
which i can convert to `DateTime` with
```
parse(DateTime, date)
```

It would be nice to have a ready made widget that does this all in one step.

**Comment by fonsp** [comment]
(Needs https://github.com/fonsp/Pluto.jl/issues/319)
