### ISSUE TITLE
slider: run on mouse release

### ISSUE THREAD

**Issue by aplavin** [fonsp/PlutoUI.jl#267]
Would be nice to have an option of `Slider` that "confirms" the value and executes dependent cells only when mouse is released - not just dragged over the slider.
Is that possible in html?

**Comment by holomorphism** [comment]
So, instead of using the `confirm` function as suggested in issue #177, you simply want to confirm the value when the mouse is released?
I also thought it would be handy to have such an option, so I created a PR.
