### ISSUE TITLE
Table of contents / Automatic enumeration of Markdown headers?

### ISSUE THREAD

**Issue by Datseris** [fonsp/PlutoUI.jl#51]
Hi there,

I use Jupyter (specifically Jupyter Lab) to make project reports every 3 months or so. As a result, the reports get quite large. I structure them in detail with markdown headers and sections. Jupyter provides an excellent extension, called simply "table of contents" that does two things:

1. Enables a table of contents sidebar that is **clickable** and brings you to the markdown header that you clicked (very useful)
2. Optionally enumerates all markdown headers with 1., 1.1, 1.2.1, etc. (nice to have, but not as crucial as the above).

Example: 

![image](https://user-images.githubusercontent.com/19669089/90527488-e2274580-e171-11ea-9df5-cd5fa23e3b9a.png)

Is this possible to be done in Pluto.jl? Is it planned?

**Comment by dralletje** [comment]
Welcomeeeee to this now fancy thread in PlutoUI 🎉

I made it work with a hybrid event/mutation observer solution, but then @pocket-titan inspired me to use mutation observer all the way down (it is possible anyway).

[Table of Content Notebook](https://mybinder.org/v2/gh/dralletje/pluto-on-binder/javascript2?urlpath=pluto/open?url=https%253A%252F%252Fgist.githubusercontent.com%252Fdralletje%252Ff38cc2a576dfccbfc348046980964bd9%252Fraw%252Fe7238f2751bbc4bcced08ac43bbf9a263846228d%252FTable-of-Content-Notebook.jl)

Right now it only links to cells, but it does index all cells. It uses one mutation observer to track when cells are added or removed, and then it uses a second mutation observer to track changes inside the output.

Removes the need for https://github.com/fonsp/Pluto.jl/pull/445 :)

**Comment by dralletje** [comment]
(Doesn't work on current Pluto release (the notebook link runs on my branch with javascript enhancements) but this will work in couple of days)

**Comment by fonsp** [comment]
Let's put this in?

**Comment by dralletje** [comment]
I will... TOMORROW

**Comment by pbouffard** [comment]
I had to search for the PR for some reason. Sparing the next person 0.5 seconds: it's #30. :)

**Comment by DhruvaSambrani** [comment]
Close?

**Comment by fonsp** [comment]
#30 thanks!

**Comment by kapple19** [comment]
Hi all, I've been trying to follow the discussions in this and related issues, and am a bit confused.

Did you guys decide to have the notebook author manually input the header/section numbers? Or has this been automated?

**Comment by g-gundam** [comment]
@kapple19 - Hopefully you've figured it out by now, but in case anyone is curious:

```julia
using PlutoUI
TableOfContents()
```

PlutoUI exports a function `TableOfContents` that will generate a table of contents for you notebook.
