### ISSUE TITLE
Memoized evaluation for sliders

### ISSUE THREAD

**Issue by DhruvaSambrani** [fonsp/PlutoUI.jl#53]
Most often sliders are used to evaluate something at different values. Can we implement a macro/function that takes some function `f(t)` to be evaluated, and a `range`.

Internally, it 
1. binds a variable t to a slider on the range `range`
2. Creates an empty array of size range and type as the return type of f
3. Creates a callable MemoizedFunction object, which has the slider, the function and t as objects

When the MemoizedFunction object is called, it evaluates f(t) and stores it in the array. At the next call, it checks whether f(t) had been evaled and returns that value, else evaluates and returns.

It also returns the slider.

I'm not sure whether this idea will work with Pluto's reactivity, but I'd be super happy if we could make it work!

**Comment by fonsp** [comment]
Have you tried https://github.com/JuliaCollections/Memoize.jl ?

**Comment by DhruvaSambrani** [comment]
I also wasn't sure whether this should go in pluto or here. Please feel free to close and reopen there if necessary

**Comment by DhruvaSambrani** [comment]
I didn't know this existed! Thanks a lot!

**Comment by DhruvaSambrani** [comment]
I suppose we can close this issue then?

**Comment by fonsp** [comment]
If you think so! Should pluto do something pluto-specific on top of that package?

**Comment by DhruvaSambrani** [comment]
I haven't closely looked at it, but do you think it is worth it to create a tiny wrapper around the package's function to automagically do memoisation? Or is it too edge case and intrusive for the user?

**Comment by DhruvaSambrani** [comment]
Also I came to this from the MIT Computational Thinking course, maybe a reference to this package in that course may be sufficient?

**Comment by fonsp** [comment]
Memoize.jl is a simple, self-contained package, I don't think that we should re-export its functionality just to make it more visible. If you search for `"memoize julia"` you should find it.
