### ISSUE TITLE
Radio button not binding values on Windows 10, Julia 1.5.2

### ISSUE THREAD

**Issue by montanonic** [fonsp/PlutoUI.jl#55]
The code `@bind temp Radio(["neat", "drop"], default="neat")` correctly creates radio buttons in the UI, and defaults to "neat". However, any click of the radio buttons leads to the bound value `temp` being set to `nothing`.

I double-checked the javascript and on cell initialization do get this error:

"CellOutput.js:200 TypeError: Cannot read property 'querySelector' of undefined"

This line being suspect: `const form = this.querySelector('#jqeekved')`. On JavaScript's strict mode, isn't a global invocation of `this` supposed to be `undefined`? As this is a top-level script block, it to mean would make sense if the script fails to execute for this reason; replacing `this` with `window` may solve the issue.

I disabled my popup blocker. Let me know if you need me to check anything else. Thanks!

**Comment by nhchan** [comment]
I am having the same issue with Julia 1.5.2 (running macOS 10.15.7 and Safari 14.0 (15610.1.28.1.9, 15610)).

**Comment by archermarx** [comment]
I am also having the same problem (Julia 1.5.2 on Windows 10 10.0.18363 build 18363 running on WSL 2)

**Comment by fonsp** [comment]
Fixed in PlutoUI 0.6.9!
