### ISSUE TITLE
Select for elements other than AbstractStrings

### ISSUE THREAD

**Issue by jonas-schulze** [fonsp/PlutoUI.jl#65]
It would be awesome if one could use `Select` on arbitrary `key => value` pairs:

```julia
names = ["Hamburg", "Berlin", "Magdeburg"]
populations = [1_900_000, 3_700_000, 240_000]

@bind city Select(pairs(names))

@show populations[k]
```

```julia
name = Dict(:hr => "Human Resources",
            :x => "Research & Development")
manager = Dict(:hr => "Jane Doe",
               :x => "Max Mustermann")

@bind division Select(name) # pairs(name) === name

@show manager[division]
```

I assume allowing `Int` and `Symbol` should cover most use cases.

### Implementation Proposal

I don't know JavaScript, so I would try to manage the state mostly in Julia. One could split the internal representation of `value => representation` into seperate arrays, so that the only exchange with the frontend would be `index::Int` corresponding to the selection (and a handle to the `s::Select` object itself, maybe its `hash(s)::UInt64`). `set_bond` would then have to be adjusted to ask the `Select` object, what the actual new value should be.

The benefit of this approach is that we don't need to deal with conversions/representations of Julia types from and to JavaScript.

A big downside of this that this would introduce a new global `Dict{UInt64,Select}` object of sorts.

**Comment by fonsp** [comment]
Thanks! Have a look at #3

**Comment by jonas-schulze** [comment]
My bad!

Over there you were discussing the problem of serializing/converting Julia objects. What do you think of my proposal to solve that problem?

**Comment by fonsp** [comment]
Yep that's also what I had in mind! https://github.com/fonsp/PlutoUI.jl/issues/3#issuecomment-629724036
