### ISSUE TITLE
[Question] is it possible to change value of a textfield

### ISSUE THREAD

**Issue by nodrygo** [fonsp/PlutoUI.jl#76]
is it possible to change a textfield value programmatically  ?
ex: 
begin
	mytxt = TextField()
	@bind txt mytxt
end
and later  something like : 
setproperty!(mytxt, :value , "az")

thanks

**Comment by fonsp** [comment]
This is not possible. Try to avoid mutation in Pluto notebook, because mutation does not trigger reactivity.

**Comment by samuela** [comment]
Something kind of like this would be very useful however. For example, consider an interactive notebook with a few sliders for interesting parameters. It's nice to let the user play with sliders. In addition, it would be great to offer buttons that trigger setting specific configurations of the `@bind` variables. This could help eg to illustrate interesting properties of whatever is being simulated.
