### ISSUE TITLE
bind to an array element or Dict value instead of just a single variable

### ISSUE THREAD

**Issue by dpgarrick** [fonsp/PlutoUI.jl#78]
Hi there,

First, thanks for making Pluto and PlutoUI, they are very cool tools.

For context, have a Pluto notebook which runs an optimisation problem using JuMP. The process involves reading in some input data files followed by a "baseline" analysis using this input dataset.  The notebook also includes a "reactive" analysis with interactive fields for some parameters. Various plots are generated of the baseline against the "reactive" results so that I can tweak parameters and see how the results compare on the fly. It works really well for the hardcoded reactive elements I am currently using. As a side note, the `confirm_combine` functionality you described in #37 would be really helpful for this notebook, as it would allow multiple of the reactive fields to be adjusted before each "reactive" optimisation run is performed. 

But, the real issue is I am now trying to extend the functionality so that some of those reactive fields are generated on the fly depending on the initial input dataset file. Basically, what that means is I want to be able to bind to an array element `	 fieldArray[i] = @bind valueArray[i] NumberField(0:1:10, default=5)` instead of a single variable `field = @bind value NumberField(0:1:10, default=5)` but everything I have tried hasn't been able to get this to work.

A simple example demonstrating more or less what I want to achieve is:
```
	valueArray = [1,2,3,4,5] # In practice, valueArray is populated from an input file
	fieldArray = Vector(undef,length(valueArray))
	for i in 1:length(valueArray)
	 fieldArray[i] = @bind valueArray[i] NumberField(0:1:10, default=5)
	end
```
where the `valueArray` is then used later in the program as part of the optimisation input data.

Unfortunately this syntax always gives an error like:
```
ArgumentError:
Macro example usage:
@bind my_number html"<input type='range'>"
```
Storing the fields in a `fieldArray`seems to work fine if they are all referencing the same singular variable `value`. I've tried all kinds of weird variations using `eval`, `Ref`, `Dict`, and others to try and pass to the bind macro a singular value which is actually the array element `valueArray[i]` but nothing has worked.

Any thoughts or suggestions would be much appreciated - even if just to say what I am trying to do is impossible!

Thanks

**Comment by fonsp** [comment]
Hey! I think that this would be a cool feature (will take some work to implement), but in the meantime we can do this on the frontend side. You could write a javascript widget that displays N numberfields, and the bound value is the array of those values.

I did something similar here: https://github.com/fonsp/disorganised-mess/blob/master/confirm%20combine.jl

**Comment by fonsp** [comment]
Hey! I'm moving this discussion to https://github.com/fonsp/Pluto.jl/discussions/923

Please take a look and feel free to contribute
