### ISSUE TITLE
Smart drop-down default

### ISSUE THREAD

**Issue by KronosTheLate** [fonsp/PlutoUI.jl#81]
Would it be possible to make it so that when one supplies `Select()` with an array of strings instead of an array of pairs of strings, it automatically creates pair with equal first and last part? I often find myself using the same string on eighter side of `=>`.

Actually, it would probably be smart to make it for a varargs method, so that one can supply a touple of strings without having to construct the array.

**Comment by pankgeorg** [comment]
Would something like this address your use case?
```julia
julia> [a => a for a in ["a", "b", "c"]]
3-element Array{Pair{String,String},1}:
 "a" => "a"
 "b" => "b"
 "c" => "c"
```

**Comment by KronosTheLate** [comment]
Yes, yes it would. Is there any reason why the method `Select(args...::String)` and `Select(A::AbstractArray{String, 1})` could not be implemented, and internally translated to `Select([a=>a for a in args])` and `Select([a=>a for a in A])` respectivly?

If there is no problem with it, I could implement it myself when I find the time.

**Comment by fonsp** [comment]
It was already implemented for `Array{<:AbstractString,1}`, but I now implemented it for `AbstractArray{<:AbstractString,1}`, I am assuming that this was the problem
