### ISSUE TITLE
Clock using with binder

### ISSUE THREAD

**Issue by dorn-gerhard** [fonsp/PlutoUI.jl#85]
I got an issue, that when using a notebook with Binder 
(e.g. https://github.com/Captain-Bayes/bayes-imoox/blob/master/notebooks/golden_nautilus_wheel.jl
with
https://pluto-on-binder.glitch.me/ )

When using
 
- *@bind n_sample_size Clock(0.2,true,false)*

I got the error

    Failed to show value:
    UndefVarError: interval not defined
    show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("text/html")}, ::PlutoUI.ClockNotebook.Clock)@Clock.jl:46
    (::Main.PlutoRunner.var"#44#45"{IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},Main.PlutoRunner.Bond})()@PlutoRunner.jl:1059
    withtag(::Main.PlutoRunner.var"#44#45"{IOContext{Base.GenericIOBuffer{Array{UInt8,1}}},Main.PlutoRunner.Bond}, ::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Symbol, ::Pair{Symbol,Symbol})@html.jl:19
    show(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::MIME{Symbol("text/html")}, ::Main.PlutoRunner.Bond)@PlutoRunner.jl:1058
    show_richest(::IOContext{Base.GenericIOBuffer{Array{UInt8,1}}}, ::Any)@PlutoRunner.jl:611
    #sprint_withreturned#28(::IOContext{Base.DevNull}, ::Int64, ::typeof(Main.PlutoRunner.sprint_withreturned), ::Function, ::Main.PlutoRunner.Bond)@PlutoRunner.jl:550
    format_output_default(::Any, ::Any)@PlutoRunner.jl:475
    #format_output#17@PlutoRunner.jl:492[inlined]
    formatted_result_of(::Base.UUID, ::Bool, ::Nothing)@PlutoRunner.jl:417
    top-level scope@none:1

When running the command locally it works fine. Could this be a version issue on the binder image?
​

**Comment by albertoguiggiani** [comment]
Have the same issue on local notebooks too.
It might be introduced with v0.7.4, the check on the interval done in Clock.jl:46 should be on clock.interval instead.
