### ISSUE TITLE
Colored with_terminal output

### ISSUE THREAD

**Issue by fonsp** [fonsp/PlutoUI.jl#88]
by @Roger-luo: the `with_terminal` output should be colored using ANSI codes.

We can use https://github.com/drudru/ansi_up for that!

**Comment by c42f** [comment]
I had occasion to want `@code_warntype` in a recent talk I did:

https://github.com/c42f/JuliaBrisbaneMeetup/blob/main/2021-04-21/julia_internals_chris_f/talk.jl

In that case, I used the following hacks with the `ANSIColoredPrinters` package and my own macros:

```
using ANSIColoredPrinters

function color_print(f)
	io = IOBuffer()
	f(IOContext(io, :color=>true))
	html_str = sprint(io2->show(io2, MIME"text/html"(),
					  HTMLPrinter(io, root_class="documenter-example-output")))
	HTML("$html_str")
end
```

```
macro code_warntype_(args...)
	code = macroexpand(@__MODULE__, :(@code_warntype $(args...)))
	@assert code.head == :call
	insert!(code.args, 2, :io)
	esc(quote # non-hygenic :(
		color_print() do io
		    $code
		end
	end)
end
	
macro code_llvm_(args...)
	code = macroexpand(@__MODULE__, :(@code_llvm $(args...)))
	@assert code.head == :call
	insert!(code.args, 2, :io)
	esc(quote # non-hygenic :(
		color_print() do io
		    $code
		end
	end)
end
	
macro code_native_(args...)
	code = macroexpand(@__MODULE__, :(@code_native $(args...)))
	@assert code.head == :call
	insert!(code.args, 2, :io)
	esc(quote # non-hygenic :(
		color_print() do io
		    $code
		end
	end)
end
```

Perhaps it would be better to do this client-side though, with `ansi_up` as you suggest?

**Comment by dralletje** [comment]
I went with the `ansi_up` approach, although I'm not sure which is "best".
Small experiment: https://gist.github.com/dralletje/4077954c56d9b594115a0f7fafdb0515
Don't have the time yet to make it into the Pluto-y terminal colors, maybe later.
